### ISSUE TITLE
TemplateContent content type is broken on Django 1.8

### ISSUE THREAD

**Issue by rodxavier** [feincms/feincms#585]
Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/Users/rodxavier/.virtualenvs/django_project/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/Users/rodxavier/.virtualenvs/django_project/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
        django.setup()
      File "/Users/rodxavier/.virtualenvs/django_project/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/Users/rodxavier/.virtualenvs/django_project/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
        app_config.import_models(all_models)
      File "/Users/rodxavier/.virtualenvs/django_project/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
        self.models_module = import_module(models_module_name)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/Users/rodxavier/workspace/django_project/webapp/cms/models.py", line 5, in <module>
        from feincms.content.template.models import TemplateContent
      File "/Users/rodxavier/.virtualenvs/django_project/lib/python2.7/site-packages/feincms/content/template/models.py", line 6, in <module>
        from django.template.loader import (
    ImportError: cannot import name Context

**Comment by matthiask** [comment]
Wow. Thank you for the report. I'm a little bit surprised that we do not have any tests in this area.

**Comment by rodxavier** [comment]
I think changing the import may fix it.

    from django.template import Context, Template, TemplateDoesNotExist

However, I'm not sure how to import find_template_loader. It seems like it's contained in the Django's new `Engine` class in `django.template.engine.py`

**Comment by matthiask** [comment]
I'm not sure whether the functionality to enumerate templates is still present. If not, we might have to rethink the way `TemplateContent` works. I haven't had the time to investigate more yet.

**Comment by dmr** [comment]
Do I read correctly that finecms doesn't work with django 1.8 because of this problem?
Did you make any progress on this issue?

**Comment by dmr** [comment]
feinCMS works fine in our projects with django 1.8 as long as we don't use TemplateContent.
Is we use TemplateContent the error occurs:

    from feincms.content.template.models import TemplateContent
    Page.create_content_type(TemplateContent)

**Comment by mjl** [comment]
Yes, TemplateContent is broken as the underlying Django mechanism for enumerating templates has changed / is gone.

**Comment by matthiask** [comment]
Here is a proposed alternative template content implementation:

https://github.com/matthiask/feincms/commit/2ad51c81158a12b620493f6786c3b05f3fa48161#diff-e83141c10d789cf42a328f779dcec96c

The templates enumeration is gone, but you get the possibility to show friendly template names to the user instead.

**Comment by matthiask** [comment]
Docs are missing, will be fixed with FeinCMS 2.0 (see commit above)
