### ISSUE TITLE
1.8 Support

### ISSUE THREAD

**Issue by typeshige** [feincms/feincms#574]
I tried with 1.8 beta 1 and after upgrading MPTT to the latest dev version, I'm getting:

Options' object has no attribute '_fill_fields_cache

**Comment by pzrq** [comment]
@typeshige You could try with https://github.com/feincms/feincms/pull/572 though from memory that PR is blocked on Django MPTT, a dependency of FeinCMS, one test still failing and probably updating `.travis.yml` instead of just `tox.ini` to actually run the tests under 1.8.

**Comment by sbaechler** [comment]
1.8 has been released on April 1st.

**Comment by nanuxbe** [comment]
Hi,

I am really interested in 1.8 support. I checked out #572 and ran the tests using django-mptt 0.7.1 with the following results:
py26-django16: Not tested (I will set that env py26 later)
py32-django17: 10 failures, 2 errors <-- is that a big deal? Since I have not seen so far (i might have missed it) any compatibility matrix?
{py27,py34}-django18: 1 failure

My question are, if I build upon #572:
* is python 3.2 a mandatory requirement for django1.7
* appart from previous question, would that 1 failure in django 1.8 be the only blocking point for merging
* is there any other requirement for a potential "next stable" release of FeinCMS compatible with Django 1.8

Cheers and thanks for the great work you've done so far

**Comment by sbaechler** [comment]
Django 1.7 runs under Python 2.7 as well. I would rather use 3.3 or 3.4 instead of 3.2 because it has better backwards compatibility with 2.7 and some libraries don't support 3.2.

**Comment by nanuxbe** [comment]
Yes, it does, sorry if I was not being clear about that, I just listed the "problem envs", not the ones working proerly which were:
* py27-django16: commands succeeded
* py32-django16: commands succeeded
* py33-django16: commands succeeded
* py34-django16: commands succeeded
* py27-django17: commands succeeded
* py33-django17: commands succeeded
* py34-django17: commands succeeded

**Comment by mjl** [comment]
Thanks for your work, we really need having FeinCMS play well with Django 1.8 as it is the next long time support release.

  Django droppend py2.6 support with 1.7, so we could live with mandating Django 1.7 and Python 2.7+ for the next release too I guess...?

  Note that I haven't been able to move any of our FeinCMS installations to >1.6 yet because they all exploded in various fun ways and it was easier to step back to 1.6 than to find the root cause, so I'm not convinced that "it passes all the tests" is enough for cutting a release.

**Comment by nanuxbe** [comment]
OK.
The 1.8 error being
AttributeError: 'ManyToManyRel' object has no attribute 'parent_model'
It is most probably related to the new model._meta api. So except if @pzrq would like to do it, I'll try to fork #572 this afternoon and see if I can fix the failure.

**Comment by pzrq** [comment]
@nanuxbe Go for it, I didn't need to get that test to pass to make FeinCMS work under Django 1.8 with our blog and learn apps.

**Comment by pzrq** [comment]
@mjl Sorry to hear that. In case it helps, from our git history, the only two kind of funny things that broke as we've upgraded from FeinCMS 1.7.7 to 1.10.1, unrelated to Django 1.7 though we're on that now too, were:

# Needed to put in the full path to the FeinCMS extension for some unknown reason
 Page.register_extensions(
-    'excerpt',
+    'feincms.module.page.extensions.excerpt',

# Threw DB table does not exist programming errors
-from feincms.module.blog.models import Entry
+from <myproject>.<myapp>.models import Entry

**Comment by nanuxbe** [comment]
As for the "Needed to put in the full path to the FeinCMS extension for some unknown reason" partn it is mentionned in the release notes (http://feincms-django-cms.readthedocs.org/en/latest/releases/1.8.html#removal-of-deprecated-features) but the documentation is indeed not up to date (I'll make the change to the docs where I've seen it mentioned when I do my PR

**Comment by nanuxbe** [comment]
Weird thing. Tox fails on my dev machine with Python 3.2.6 / Django 1.8 but work with on travisci with 3.2.5...

**Comment by matthiask** [comment]
The template content does not work, apart from that FeinCMS works well with Django 1.8.
